### PR TITLE
Adding the ability to map ports to containers when running them.

### PR DESCRIPTION
**Pull request by amcguier**
I'd consider this patch experimental, but I wanted to get the idea out there.

For my typical use case it would be pretty useful to be able to map ports to containers as part of the run command. 
It raises a couple of questions.

1.) Should this be default prompted behavior, or a separate run function ?
2.) As in this example, should I allow mapping a default port, or maybe a space separated list of mappings per container.
3.) Should the command argument be uniformly applied to all selected images, or should we prompt for the command on each container via the same mechanism I'm using for ports.

My emacs-lisp skills are fairly rudimentary so any cleaner way to do this would also be appreciated. If you have strong feelings about which way to go, I'd be happy to rework this patch and redo the pull request.

### CODE REVIEW

**Comment by Silex** [comment]
Hello & thanks!

I think theorically, it'd be nice if one could specify the ports and the volume as part of the run popup. So far I did not start implementing this because it relies on magit-popup, which is meant to be rewritten by @tarsius one day, but until then it only has support for one argument... that said, I just realised we could already provide it even for one argument! It's better than nothing.

We could also invent "new" flags that would just contain the list of other flags to pass.

Here's what I have in mind:

``` elisp
(magit-define-popup docker-images-run-popup
  "Popup for running images."
  'docker-images-popups
  :man-page "docker-run"
  :switches '((?d "Daemonize" "-d")
              (?i "Interactive" "-i")
              (?t "TTY" "-t")
              (?r "Remove" "--rm"))
  :options  ((?v "volume" "-v ")
             (?e "environment" "-e ")
             (?p "port" "-p "))
  :actions  '((?R "Run images" docker-images-run-selection))
  :default-arguments '("-i" "-t" "--rm"))
```

This would *already* work but it only allows to specify ONE volume, port or environment var. To pass *multiple* ports, I could image some kind of smart `-P` option with a helper and some manipulation before running the command (to turn `-P a b c` into `-p a -p b -p c`.

@tarsius: just to be sure, do you see a way to have multiple user input for the same option? Or is the only trick to add a "virtual" option that get splitted later on?

**Comment by Silex** [comment]
I just added https://github.com/Silex/docker.el/commit/ad94d10f792f619f746d2568b81dc93e902219b0, it works nicely! Now we just need to figure how to support multiple occurence of the option.

**Comment by amcguier** [comment]
@Silex Nifty!

I was also curious what your take was on the where do do the prompts. If you've selected multiple containers, does it make sense to provide the -p or -v flags at the top level, since the port bindings would conflict? Or would the assumption be that the user would only select one container at a time when applying those flags ?

**Comment by Silex** [comment]
@amcguier: hum, good catch... I think *for now* it makes more sense to just let the user do wrong thing, because there's still so much other important features to implement. But in the future, maybe some options could be "greyed out" if there is more than one image selected.

**Comment by Silex** [comment]
Hehe, I experimented a bit and these virtual flag works nicely! Checkout the latest source. Also, if you update `tle` you'll discover that marking rows is now highlighted.

I'm very close to be able to specify commands directly in the popup!

**Comment by Silex** [comment]
Alright, check what I just pushed. I added a virtual `--command` popup option

**Comment by Silex** [comment]
@amcguier: should this PR stay open?

**Comment by tarsius** [comment]
Is my help still needed?

**Comment by Silex** [comment]
@tarsius: can you confirm that `magit-popup` has not support for "recurring" options? e.g a command that goes `docker-run -v foo:bar -v baz:keke -v woot:woot`

That is, we need to specify `-v` several times... I can image two solutions:

- Create options like `=x`, `=y`, `=z` which are processed later on and where `-[xyz]` is replaced by `-v`
- Create one option like `=v` with a custom reader that is processed later on.

Wait I just realised... can't you simply pass the other `-v` flags as part of the option? let's test

-

**Comment by Silex** [comment]
**bwahahahaha yes it works**

@tarsius: thanks and ignore my previous requests, `magit-popup` is awesome.

**Comment by tarsius** [comment]
The "Limit to files" option of the various log popups does something similar. See `magit-read-files`, `magit-log-arguments`, and `magit-popup-export-file-args`. It's a bit complicated because you will no longer be able to use `magit-define-popup` and have to define the various variables and functions manually (or you could just advice the `*-arguments` function, but seems dirty).

> Wait I just realised... can't you simply pass the other -v flags as part of the option?

Huh? Please let me see that.

**Comment by Silex** [comment]
>> Wait I just realised... can't you simply pass the other -v flags as part of the option?

> Huh? Please let me see that.

With https://github.com/Silex/docker.el/blob/master/docker-images.el#L174, pressing </kbd>=v 80:80 -v 443:443</kbd> works. That is, you explicitely write additionals `-v` as part of the option. The resulting option is `-v 80:80 -v 443:443`.

It's just a trick.

**Comment by tarsius** [comment]
This might cause issues somewhere a long the way. But even if it doesn't I would recommend going with a `completing-read-multiple` wrapper and then splitting that up into multiple arguments in `*-arguments`.

**Comment by Silex** [comment]
@tarsius: ah, interesting. I'll play with it, thanks! Btw, do you know a way to "force-reload" a `magit-define-popup` ? Right now the only way I find it either give it a new name and use the new name or quit emacs and start it again... kinda annoying when you develop a new popup :)

**Comment by tarsius** [comment]
`eval-defun`

**Comment by Silex** [comment]
Thanks a lot

**Comment by tarsius** [comment]
> that's just `C-M-x`

Not in my case, that's why I mentioned only the command :-)

> it does not work, not refreshing modified options.

It doesn't? It does for me. I guess the problem is that when using `docker-utils-define-popup`, then the variable definitions are one macro expansion further away.

**Comment by Silex** [comment]
Well, if it does work for you then the problem must be on my side. It'll probably be gone the next time I upgrade emacs. Thanks anyway!

**Comment by amcguier** [comment]
I'm suspecting we can probably close this pull request and move the discussion onto an issue?  I'm assuming you'd rather use the magit popup mechanism and not the version I implemented here.

**Comment by Silex** [comment]
@amcguier: did you check the latest changes? the docker-run popup now allows to specify ports, environment variables, volumes...

**Comment by amcguier** [comment]
I did, that looks awesome. I'm going to close this PR.

Thanks!

**Pull request closed without merging**
