### PR TITLE
Implement docker-logs

### PR DESCRIPTION
**Pull request by Yuki-Inoue**

### CODE REVIEW

**Comment by Silex** [comment]
Can you make the definition "Popup for showing containers logs." and then squash all the commits into one? If not I'll just do it myself later :)

**Comment by Yuki-Inoue** [comment]
squashed!

**Comment by Yuki-Inoue** [comment]
Oh, I've missed your request. Wait a while, I'll fix...

**Comment by Yuki-Inoue** [comment]
Fixed!

**Comment by Silex** [comment]
Thanks! :clap:

**Pull request merged**
