### PR TITLE
Switch to transient.el

### PR DESCRIPTION
**Pull request by Silex**
Work in progress

### CODE REVIEW

**Comment by Silex** [comment]
@tarsius I have a few questions if you are ok. So far the convertion looks simple enough but I just want you to confirm a few things and point me to the right direction for others.

* Popups default suggested arguments like in https://github.com/Silex/docker.el/blob/master/docker-image.el#L55 should be replaced with `:value` like in https://github.com/magit/magit/blob/master/lisp/magit-blame.el#L895 ?
* What is the equivalent of `:setup-function` now? the goal is to run some code when the popup is invoked, see https://github.com/Silex/docker.el/blob/master/docker-utils.el#L46-L49

**Comment by tarsius** [comment]
I am okay, thanks for asking. My elbow hurts a little; from resting on it for too long I believe. Oh, that's not what you meant. :wink: 

1. Yes.
2. I am guessing that `tablist-put-mark` does not affect the transient and its arguments, but state in some other buffer. Does this have to happen after the transient has been created or could it be done before?

   `:setup-function` was mainly intended to work around limitations of `magit-popup`, which is why there is no equivalent "hook" now. Transient used generic functions for things that I believe should be customizable, but `transient-setup` is not one of those things.

   The new way of "doing other things" when showing the popup is to do so in the body of the transient prefix command. Copy [the default body](https://github.com/magit/transient/blob/a87cb2c35ace612d1e1f7fc51264baac49a5708b/lisp/transient.el#L571-L573) that is used if no explicit body is given and make the necessary adjustments. Maybe `magit-show-refs` can serve as an example (though it does something different).

**Comment by Silex** [comment]
> I am okay, thanks for asking. My elbow hurts a little; from resting on it for too long I believe. Oh, that's not what you meant. :wink:

:smile: I hope you are ok man!

Alright, thanks for the pointers, will ping you if necessary but it looks simple. The library is indeed simpler/cleaner than magit-popup, congrats!

**Comment by Silex** [comment]
Alright, getting there :sweat_smile: Still have to figure a few quirks but soon we'd be able to test.

**Comment by Silex** [comment]
Okay, almost there! Just a bit of refactoring and I'll merge soon.

@chrislong, @seagle0128: if you could test a bit it'd be nice

**Comment by Silex** [comment]
Done :tada:

**Pull request merged**
