### PR TITLE
Add docker compose

### PR DESCRIPTION
**Pull request by Silex**

### CODE REVIEW

**Comment by mzgnr** [comment]
@Silex a friendly ping for this PR 😄

**Comment by Silex** [comment]
@mzgnr: thanks for reminding me :sweat_smile: 

I really need to find some time!

**Comment by Silex** [comment]
Alright, I'd have some time to at least prepare the next steps.

While working on the list at https://github.com/Silex/docker.el/issues/6, I realise docker is heading in the direction `docker container run` instead of `docker run`, which makes it easier to planify.

**Comment by Silex** [comment]
@olymk2: maybe we could merge or find some way to collaborate with https://github.com/olymk2/emacs-docker-compose?

I should soon work on #53, which would be some kind of "docker status" from where you can jump to the already existing containers/images/volumes/etc listings. We can maybe find a way to add your work on docker-compose to this kind of "docker status" interface.

The thing is containers/images/volumes etc are "global" resources that can be accessed from everywhere, while docker-compose is something "local"... so maybe mixing these interfaces is not such a good idea.

Anyway, I can see several path of collaboration:
- You continue working on your own package and I just list it as related packages
- You continue working on your own package but we work common a similar interface, and thus my package simply depends on yours and "delegate" the integration to your package.
- We import/merge your work here, and I add you as a collaborator and you're responsible for maintaining the docker-compose part.

**Comment by olymk2** [comment]
@Silex I was having a look I think which ever root we can share some code, I think some of the things i have done you may not have done yet for example this  does not block for the most part, which i noticed there was an issue for in your. equally yours looks more complete functionality wise I have only exposed a few commands and flags so far.

I agree with the local and global, which is why i support both some projects I have a compose file but equally other have a dockerfile which it would be nice to build quickly.

I don't really mind on the root taken, my main goal is to just have one launcher like magit which i can drill into compose or docker as needed to build launch and run commands in particular I want to be able to send unit test commands into the container in the future.

I will play with yours a bit more, i liked the table you had for the containers and images, not sure if you can press a key to interact with the container from those screens ?

**Comment by Silex** [comment]
> @Silex I was having a look I think which ever root we can share some code, I think some of the things i have done you may not have done yet for example this does not block for the most part, which i noticed there was an issue for in your. equally yours looks more complete functionality wise I have only exposed a few commands and flags so far.

I'll look about how you tackle the non-blocking part.

> I will play with yours a bit more, i liked the table you had for the containers and images, not sure if you can press a key to interact with the container from those screens ?

Yes you can, see https://github.com/Silex/docker.el#docker-containers

Basically, you can open a shell inside the container or a file from the container. There's no support for quick exec at the moment, but that's easy to add.

**Comment by olymk2** [comment]
cool, you can see how i have done it in this function, https://github.com/olymk2/emacs-docker-compose/blob/master/dc-popups-core.el#L120 one thing I have not figured out is how to make the buffer scroll as the worker outputs, but I basically pass most things through that function now.

I will try out the shortcuts, perhaps thats another thing to add ? for a list of shortcuts I like having a way to discover them as I often forget them :)

**Comment by Silex** [comment]
Yeah, the `?` shortcut is also planned :)

**Comment by dakra** [comment]
Is there any news on this as it looks like this MR is almost ready?
Anything I could help with to move it forward?
Thanks :)

**Comment by Silex** [comment]
Unfortunately it is hard to move forward with this until https://github.com/Silex/docker.el/issues/53 is not resolved.

I hope to find some time soon but everytime I said that I got swamped. Let's hope this will change :pray:

**Comment by dakra** [comment]
With #53 merged I feel this is a good time for a friendly bump ;)

**Comment by Silex** [comment]
@dakra: yep, soon on my todo list :wink:

**Comment by Silex** [comment]
@dakra, @shackra, @mzgnr: you guys can test https://github.com/Silex/docker.el/tree/docker-compose

Originally, I did a listing like `docker-compose ps` does, which you can still check before I removed it by running <kbd>M-x docker-compose-ps</kbd>, but then I thought this listing was silly:

* It takes away the `U` key for `docker-compose-up`
* The listing in itself is limited compared to `docker-containers`
* It'd be better to have something magic that displays `docker-containers` but filtered on the current `docker-compose` file (e.g the `c` key). Then you can use the containers listing interface instead.

Anyway, to test use <kbd>M-x docker-compose</kbd>

**Comment by dakra** [comment]
@Silex thanks.
If I have a `docker-compose.yml` open I can call your docker-compose commands,
but when I'm somewhere else in my project not.

Would be nice if I can specify which compose files it should take.

E.g. for one project I call docker-compose like:
`docker-compose -p projectname -f docker/docker-compose.yml -f docker/project-admin.yml up`

I would like a defcustom list for the files so I can change them in my
dir-locals for each project.

I would also like a `run` option.
Example from one of my projects Makefile again:
`docker-compose -f docker/test.yml run --rm app bash -c "make jstest $(args)"`

(PS: I couldn't get `docker-compose-ps` to work at all.
Always errors with `Supported filenames: docker-compose.yml, docker-compose.yaml`)

Thanks

**Comment by Silex** [comment]
> Would be nice if I can specify which compose files it should take.

Right, you remember me that I wanted to add this to all popups (like the services), but...

> I would like a defcustom list for the files so I can change them in my
> dir-locals for each project.

...this also makes sense. Given the more "permanent" nature of these files list, I'll go for defcustom.

> I would also like a run option.

Of course! I simply forgot about it :sweat_smile: 

> (PS: I couldn't get docker-compose-ps to work at all.

Weird. I'll try to find why.

**Comment by dakra** [comment]
> Given the more "permanent" nature of these files list, I'll go for defcustom

Maybe the defcustom should just pre-fill the popup options?
That way I could manually switch to another file for testing or something.

**Comment by Silex** [comment]
> Given the more "permanent" nature of these files list, I'll go for defcustom
> 
> Maybe the defcustom should just pre-fill the popup options?
> That way I could manually switch to another file for testing or something.

Good idea :+1:

**Comment by Silex** [comment]
Alright good progress being made, need to work out the last bits.

**Comment by Silex** [comment]
@dakra, @shackra, @mzgnr: merging soon! Only need to implement https://github.com/Silex/docker.el/pull/39/commits/bfaae02e6f604a559178b107a5bc7a5e203fb100 and even this can be done after the merge.

**Comment by dakra** [comment]
@Silex Great, thanks. I'll have a look at it and comment on Sunday/Monday.

**Comment by Silex** [comment]
@dakra: btw, for multiple docker-compose files there's a limitation with magit-popup, you have to type it like so:

* press `-f`
* Enter `docker/docker-compose.yml -f docker/project-admin.yml`

That'll end up in `-f docker/docker-compose.yml -f docker/project-admin.yml`

You can also modify the `docker-compose-arguments` variable.

**Comment by dakra** [comment]
@Silex sorry for the late reply, I'm very busy these days.
I gave it a quick test and worked pretty nice for my case.

The only thing I noticed is that the autoloads are wrong/missing.
for `docker-compose` it's missing completely and should be:
`;;;###autoload (autoload 'docker-compose "docker-compose" nil t)`

And for `docker` it needs to be changed to
`;;;###autoload (autoload 'docker "docker" nil t)`

Otherwise it will complain.

And the docker-compose Run should be 'R' and 'R' again
not 'R' and 'O'.

Otherwise I would say this can be merged and new features/changes
can be aded later.

Thank you very much.

**Comment by Silex** [comment]
> The only thing I noticed is that the autoloads are wrong/missing.
> for docker-compose it's missing completely and should be:
> ;;;###autoload (autoload 'docker-compose "docker-compose" nil t)
> 
> And for docker it needs to be changed to
> ;;;###autoload (autoload 'docker "docker" nil t)
> 
> Otherwise it will complain.
> 
> And the docker-compose Run should be 'R' and 'R' again
> not 'R' and 'O'.

Thank you a lot for the mini code review! :+1: 

I'll adjust some things and merge it soonish.

**Pull request merged**
