### PR TITLE
Support \t and \n on container info

### PR DESCRIPTION
**Pull request by Yuki-Inoue**
Output and parse container information via json so that it can parse \t
and \n characters included in the container information correctly.

Also refer: #2

### CODE REVIEW

**Comment by Silex** [comment]
Thanks... I'll cleanup some useless things tho :-)

**Comment by Yuki-Inoue** [comment]
@Silex I thought that the helper was needed to handle newline properly. Now I realized the json formatting of golang template escapes the newline character into '\n', which means that the helper was in fact useless.

Anyway, thanks for the cleanups :-)

**Comment by Silex** [comment]
No worries, thanks for the PR!

**Comment by tzz** [comment]
Lovely :)

**Pull request merged**
