### PR TITLE
Manually choosing shell when prefix argument is passed in shell popup

### PR DESCRIPTION
**Pull request by dcluna**
Motivation: I was working with a multi-stage build and I had to check the filesystem of an image whose default shell wasn't the one I specified in `docker-container-shell-file-name`, so I added this.

Please let me know if there is a better way of achieving this, or if this can be accomplished in a different way.

### CODE REVIEW

**Comment by Silex** [comment]
Thanks!

Hum, I wonder if `(defun docker-container-shell (container &optional shell)` would not make more sense.

If prefix then read-string, if absent then default to `docker-container-shell-file-name`...

**Comment by dcluna** [comment]
Hey @Silex , just pushed a commit that _should_ make the intent of the option clearer. I _think_ we still want to read the shell in both functions because both are interactive - so even though `docker-container-shell-selection` is the entrypoint for the other function, it's still possible that the latter will be called interactively elsewhere.

WDYT?

**Comment by Silex** [comment]
Hum sorry I was a bit busy. Can you squash the commits together? I'll merge it for now and probably refactor it a bit later.

**Comment by dcluna** [comment]
@Silex done, can you re-review?

**Comment by Silex** [comment]
Thanks!

**Pull request merged**
