### PR TITLE
transient keys need not match switch names

### PR DESCRIPTION
**Pull request by gitonthescene**
Hey there,

I don't think the leading dash adds any value here.  It's just more typing.  Also, it's misleading for cases where the "switch" doesn't exist in the underlying docker command like -M for --mount.

Regards,
-Doug

### CODE REVIEW

**Comment by Silex** [comment]
Thanks a lot! It makes total sense.

That happened because it was ported from magit-popup, where you had to use dashes.

**Comment by gitonthescene** [comment]
Awesome!  Thanks.

BTW, I don't know if you got an answer to [this question](https://github.com/magit/transient/issues/51#issuecomment-553520197) or not, but I think the answer is that there is not a substantive difference.  Superficially it looks like you can supply keywords with the `define-suffix-command`, but they can also be supplied in the group spec as well.  Either way, these keywords are simply passed to the object representing the value when it's created.  I.e they both boil down to calling `(transient-suffix args)`, but using `define-suffix-command` adds an extra keyword with the name of the command whereas in the spec case an auto-generated command name is added.

I think it's just a style choice of where you'd best like to organize that input.  Or maybe the parsing of keywords in the group spec came later and made the use of define-suffix-command unnecessary.  I don't know the history at all.

FWIW, I'm taking some time to make a study of the transient code and plan on doing a write-up of it.  The manual is pretty impenetrable.  I think the key to unlocking more sophisticated behavior is in supplying a :class for the suffix function.  My short term goal is to add support for options which can occur more than once like -v for docker-image.

**Comment by Silex** [comment]
@gitonthescene: awesome! yes I could use a lot of your help deciphering how transient works for more complex things. What you are researching for `-v` flags in docker image run will directly be used in #137, make sure to see what tarsius recommended there.

**Comment by Silex** [comment]
By the way if you have time to spare, finding how to reuse magit-process in order to run the docker commands asynchronously, in a buffer of their own (`$` key in magit) is a long goal of this project, but I never find the time.

**Comment by gitonthescene** [comment]
Thanks for the pointers.  I'll try to have a look to understand what you're trying to do.

**Pull request merged**
