### PR TITLE
Customizing docker-compose run buffer name

### PR DESCRIPTION
**Pull request by dcluna**
Just so I could have a `docker-compose run` buffer automatically named after the command it is running. Seems like it could be useful for other people, so here it is.

### CODE REVIEW

**Comment by Silex** [comment]
Thanks!

Looking at the implemention, I think this makes more sense:

``` elisp
(defun docker-compose-make-buffer-name (action args)
  (format "*docker-compose %s (%s)*" action (s-join " " args)))
  
(defcustom docker-compose-run-buffer-name-function 'docker-compose-make-buffer-name
  "Names a docker-compose run buffer based on `service' and `command'"
  :group 'docker-compose
  :type 'function)

(defun docker-compose--run-async (action &rest args)
  "Execute docker ACTION passing arguments ARGS."
  (let ((command (format "docker-compose %s %s %s"
                         (s-join " " docker-compose-arguments)
                         action
                         (s-join " " (-flatten (-non-nil args))))))
    (message command)
    (async-shell-command command (funcall docker-compose-run-buffer-name-function service args)) args service command))
```

What do you think? I could even argue that the defcustom would become a bit useless and the default "good" enough :wink: At the same time it allows for customization only for the `docker-compose run` command, with some `if` inside `docker-compose-make-buffer-name`;

**Comment by dcluna** [comment]
@Silex The reasoning behind this less-than-ideal implementation was that my custom function looks like the following: https://github.com/dcluna/dotfiles/blob/master/spacemacs.org#docker

I researched a bit for an easy (read that as "one-liner" or "convenient macro") way to get the `service` and `command` `kwargs` through elisp, but couldn't find anything. Since I _assume_ people will want to do something in this area (maybe doing some logic around the service/command name?), it felt like the best option. WDYT?

**Comment by Silex** [comment]
@dcluna: I'm not sure I follow, because my implementation does the same thing? Anyway, you could always customize with:

``` elisp
(defun docker-compose-make-buffer-name-for-dcluna (action args)
  (if (string-equal action "run")
      (format "*%s %s*" action (car args))
    (format "*docker-compose %s (%s)*" action (s-join " " args)))
```

Do you want me to make a branch of my idea so you get to try it? Originally I wanted you to modify the PR so you get to be the author of the change, but I can also do it.

> I researched a bit for an easy (read that as "one-liner" or "convenient macro") way to get the `service` and `command` kwargs through elisp, but couldn't find anything.

Using `dash`, something like:

``` elisp
(-let ((service command) (-butlast 2 args))
  (format "*%s %s*" service command))
```

**Comment by Silex** [comment]
@dcluna: can you give https://github.com/Silex/docker.el/tree/customizable-buffer-name a try?

If you want exactly your output:

``` elisp
(defun dcluna-make-buffer-name (action args)
  (if (string-equal action "run")
      (-let ((service command) (-take-last 2 args))
        (format "*%s %s*" service command))
    (docker-compose-make-buffer-name action args)))
(setq docker-compose-run-buffer-name-function 'dcluna-make-buffer-name)
```

**Comment by Silex** [comment]
@dcluna: ping

**Comment by dcluna** [comment]
@Silex Sorry for not getting back to this earlier, New Year's recess got me.

I just tried your branch and it works well. Would you prefer that I close this PR then?

**Comment by Silex** [comment]
Alright, I'll merge the branch then. Thanks for the feedback.

**Pull request closed without merging**
