### PR TITLE
Add docker-container-attach

### PR DESCRIPTION
**Pull request by Silex**
@dcaixinha: can you give it a try and report?

### CODE REVIEW

**Comment by Silex** [comment]
@dcaixinha: ping

**Comment by dcaixinha** [comment]
hey @Silex, sorry for the unresponsiveness. I'll try this branch out tomorrow morning and report back!

**Comment by Silex** [comment]
Merged :wink:

**Comment by dcaixinha** [comment]
Sorry @Silex, I was having some issues configuring my Emacs to use a branch instead of directly from MELPA. I have now updated my package and tested it on `master` and it's working as expected :ok_hand: thanks :raised_hands: :100:

**Pull request closed without merging**
