### PR TITLE
docker-machine-env windows problems

### PR DESCRIPTION
**Pull request by davidshen84**
Double escape "\".

### CODE REVIEW

**Comment by Silex** [comment]
Can you reword the commit to something more meaningful? 

For example: `Properly escape "\" for docker-machine-env on windows`.

**Comment by davidshen84** [comment]
I update the commit message. Please take a look.

As I added in the comment for issue #50. I found this issue on Windows, but this issue is caused by the `read` function which is platform invariant. Since we use `read` on each of the command output, any variable contains double **\\** will trigger this issue.

For our particular case, we use `read` to process the output from `docker-machine env`. Only `DOCKER_CERT_PATH` would possibly have **\\** in it.

- On Windows, it almost always happens. Because it uses **\\** as the path separator
- On Linux, it is unlikely to happen. Because it is not a common practice to use **\\** in a path.

So the `s-replace` I added will only update the variable when:

- It is on Windows
- It is processing `DOCKER_CERT_PATH`

In other cases, it is just a non-op.

**Comment by Silex** [comment]
> I update the commit message. Please take a look.

Well, at the moment the commit is still named `Resolve Silex/#50` with a subcomment `Properly escape "\" from shell output`.

The idea was to replace it all with `Properly escape "\" from shell output` :wink: 

Aaaanyway, I thought about it and the whole code using `read` looks like a hack. I think @benswift used this because it was a quick & easy way to parse the strings.

Can you paste me what the output of `docker-machine env foo` looks to you?

I think a better fix is this:

``` diff
diff --git a/docker-machine.el b/docker-machine.el
index aaf47cb..9db9d08 100644
--- a/docker-machine.el
+++ b/docker-machine.el
@@ -98,9 +98,10 @@
   (docker-machine "start" name))
 
 (defun docker-machine-env-export (line)
-  (let ((split-string (s-split "=" (s-chop-prefix "export " line))))
-    (setenv (car split-string)
-            (read (cdr split-string)))))
+  (let ((index (s-index-of "=" line)))
+    (unless index
+      (error (format "Cannot find separator in %s" line)))
+    (setenv (substring line (length "export ") index) (substring line (+ 2 index) -1))))
```

**Comment by Silex** [comment]
@davidshen84: can you test with https://github.com/Silex/docker.el/blob/fix-docker-machine-env/docker-machine.el ? I think it should fix the problem and be more elegant.

**Comment by davidshen84** [comment]
@Silex I tried it out, and it works. I think it is a better solution.

**Comment by Silex** [comment]
Alright, thanks :+1:

**Pull request closed without merging**
