### PR TITLE
docker inspect on images supported

### PR DESCRIPTION
**Pull request by Yuki-Inoue**

### CODE REVIEW

**Comment by Silex** [comment]
:+1:

**Comment by tzz** [comment]
@Yuki-Inoue terrific. I wonder if it makes sense to at least turn on JSON highlighting in the popup buffer, and maybe even show the information in some kind of tree format (but you should be able to toggle between JSON and tree views). What do you think? If you and @Silex agree, I could give it a try.

**Comment by Silex** [comment]
Yes, simply enable `json-mode` in that buffer.

**Comment by Yuki-Inoue** [comment]
json mode, I agree (but in that case, I assume we need to take care of the `*docker-result*` buffer in different command outputs such as `docker logs`).

About the tree view, I assume you'll be showing something like yaml.  Sounds fine for me.

**Comment by Silex** [comment]
Yes, but I'd start simply by calling `json-mode` in those buffers.

The tree view can wait IMHO, but if I had to do it I'd use `hs-minor-mode` as recommended on https://www.reddit.com/r/emacs/comments/33djht/navigating_large_json_documents/

**Comment by tzz** [comment]
@Yuki-Inoue do you want me to try the patch or will you? I am not sure about your "need to take care" comment, I assume you mean because the popup code is shared between several commands?

@Silex thanks, I'll add that `hs-minor-mode` after the main `json-mode` call is added. Good idea, I didn't know about this clever use of it.

**Comment by Silex** [comment]
@tzz: based on your initial comment we both assumed you wanted to write the commit yourself. We were merely talking out loud about the things you'd need to do.

About `hs-minor-mode`, you need to verify how it works and if it makes sense to use it there. Personally only `json-mode` is already a good improvement.

**Comment by tzz** [comment]
OK, PR coming soon, thanks!

**Pull request merged**
